# -*- coding: utf-8 -*-
"""pyramid_zeynepduman_elifaskin.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XE8Kq5G7BiXcSVHA4sX3Dj9AS3XUalkc
"""

#This game is designed by Zeynep İrem Duman and Elif Aşkın.However,the code was written induvidually.
import random
def pyramid_zeynepduman_elifaskin():
  print ('WELCOME TO PYRAMID GAME!')
  print ('This game is inspired by the food chain in its design.')
  print ('RULES:We have 3 character.Lion,Elephant and Crocodile.Lion eats crocodile.Crocodile eats elephant.Elephant eats lion.Law of the nature 😜')
  print('The player who leads 2 points wins the game.Good Luck!')
  choices = ["lion", "elephant", "crocodile"]
  user_score = 0
  computer_score = 0

  while True:
     user_choice = input("Lion, Elephant or Crocodile? (If you don't want to play write 'exit'): ")
     if user_choice == 'exit':
            print("GAME OVER 😡")
            break

     if user_choice not in choices:
            print('Invalid choice .Please try again 😯')
            continue

     #Determine the selection of the computer.
     computer_choice = random.choice(choices)

     print (f"Your choice: {user_choice}")
     print(f"Bilgisayarın seçimi: {computer_choice}")

     #Check the game result
     if user_choice == computer_choice:
            print("Scoreless.Try again 🙂")
     elif (
            (user_choice == 'lion' and computer_choice == 'crocodile') or
            (user_choice == 'elephant' and computer_choice == 'lion') or
            (user_choice == 'crocodile' and computer_choice == 'elephant')
        ):
            print("Congrats! You win 🥳")
            user_score += 1
            print(f"Score: You {user_score} - {computer_score} Computer")


     else:
            print("Sorry! You lost 🥹")
            computer_score += 1
            print(f"Puan Durumu: You {user_score} - {computer_score} Computer")

     #Check the game. The game is won by the player who leads 2 point wins the game
     if abs(user_score - computer_score) == 2:
      if user_score > computer_score:
               print("Game finished.Congrats,you won🥳🥳")
      else:
            print("Game finished.Sorry,you lost 🥹🥹")

      play_again = input("Do you want to play? (yes/no): ")
      if play_again.lower() != 'yes':
       print("Game finished.Good bye!")
       break
      else:
       print("New game will start!")
       user_score = 0
       computer_score = 0